from typing import Protocol

from src.domain.entities import DataRecord


class DataRepository(Protocol):
    def create(self, title: str, content: str, data_type: str) -> DataRecord: ...

    def list(self) -> list[DataRecord]: ...

    def get(self, record_id: int) -> DataRecord | None: ...

    def update(self, record_id: int, title: str, content: str, data_type: str) -> DataRecord: ...

    def delete(self, record_id: int) -> None: ...


class Encryptor(Protocol):
    def encrypt(self, value: str) -> str: ...

    def decrypt(self, value: str) -> str: ...
